---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helm-operator
  namespace: fluxcd
  labels:
    app: helm-operator
    release: helm-operator
    tier: cluster
spec:
  endpoints:
    - port: http
      honorLabels: true
  namespaceSelector:
    matchNames:
      - fluxcd
  selector:
    matchLabels:
      app: helm-operator
      release: helm-operator
