---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helm-operator
  namespace: fluxcd
  labels:
    app: helm-operator
    release: helm-operator
    tier: cluster
spec:
  endpoints:
    - port: http
      honorLabels: true
  namespaceSelector:
    matchNames:
      - fluxcd
  selector:
    matchLabels:
      app: helm-operator
      release: helm-operator
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus
    tier: cluster
  name: helm-operator-rules
  namespace: fluxcd
spec:
  groups:
    - name: helm_operator.rules
      rules:
        - alert: HelmOperatorLowThroughput
          annotations:
            message: 'Low queue throughput'
          expr: flux_helm_operator_release_queue_length_count > 0
          for: 30m
          labels:
            severity: warning
        - alert: HelmReleaseRolledBack
          annotations:
            message: 'Automatic rollback of HelmRelease'
          expr: flux_helm_operator_release_condition_info{condition="RolledBack"} == 1
          labels:
            severity: warning
        - alert: HelmReleaseError
          annotations:
            message: 'HelmRelease subject to an error'
          expr: flux_helm_operator_release_phase_info{condition="Released"} == -1
          labels:
            severity: warning
