---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-profile
  namespace: istio-system
spec:
  hub: docker.io/istio
  tag: 1.8.0
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 50
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            metallb.universe.tf/address-pool: "production"
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.77.105
    egressGateways:
      - name: istio-egressgateway
        enabled: false
  values:
    global:
      tracer:
        zipkin:
          address: "jaeger-operator-jaeger-collector-headless.jaeger-operator:9411"
