---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-profile
  namespace: istio-system
spec:
  profile: default
  values:
    grafana:
      enabled: false
    prometheus:
      enabled: false
    tracing:
      enabled: false
    kiali:
      enabled: false
    certmanager:
      enabled: false
    global:
      tracer:
        zipkin:
          address: "jaeger-operator-jaeger-collector-headless.jaeger-operator:9411"
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 50
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
    egressGateways:
      - name: istio-egressgateway
        enabled: true
