---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: istio-prometheus
    tier: istio
  name: istio-prometheus
  namespace: istio-system
spec:
  alerting:
    alertmanagers:
      - name: alertmanager-operated
        namespace: monitoring
        port: web
  externalUrl: http://istio-prometheus.demo.lab
  enableAdminAPI: false
  scrapeInterval: 15s
  scrapeTimeout: 10s
  evaluationInterval: 15s
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  replicas: 1
  retention: 6h
  routePrefix: /
  ruleSelector:
    matchLabels:
      tier: istio
  serviceAccountName: istio-prometheus
  serviceMonitorSelector:
    matchLabels:
      tier: istio
