---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: jaeger-operator
spec:
  values:
    jaeger:
      create: true
      spec:
        strategy: allInOne
