---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: kiali-operator
spec:
  values:
    cr:
      create: true
      name: kiali
      namespace: "istio-system"
      spec:
        istio_component_namespaces:
          prometheus: monitoring
          tracing: jaeger-operator
          grafana: monitoring
        auth:
          strategy: "anonymous"
        deployment:
          accessible_namespaces:
            - '**'
          external_services:
            custom_dashboards:
              prometheus:
                url: "http://prometheus-operated.monitoring:9090"
              namespace_label: kubernetes_namespace
            tracing:
              enabled: true
              auth:
                insecure_skip_verify: true
                type: "none"
              in_cluster_url: "http://jaeger-operator-jaeger-query.jaeger-operator:16686"
              url: "https://tracing.demo.lab"
            grafana:
              enabled: true
              auth:
                insecure_skip_verify: true
                type: "none"
              in_cluster_url: "http://kube-prometheus-stack-grafana.monitoring:80"
              url: "https://grafana.demo.lab"
            prometheus:
              auth:
                insecure_skip_verify: true
                type: "none"
              url: "http://prometheus-operated.monitoring:9090"
