---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    commonLabels:
      tier: cluster
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    grafana:
      grafana.ini:
        server:
          root_url: http://grafana.demo.lab
      additionalDataSources:
      - name: Jaeger
        type: jaeger
        access: proxy
        uid: jaeger_ds
        url: http://jaeger-operator-jaeger-query.jaeger-operator:16686
      dashboards:
        default:
          istio-mesh:
            gnetId: 7639
            revision: 43
          istio-service:
            gnetId: 7636
            revision: 43
          istio-workload:
            gnetId: 7630
            revision: 43
          istio-performance:
            gnetId: 11829
            revision: 43
          istio-control-plane:
            gnetId: 7645
            revision: 43
    alertmanager:
      alertmanagerSpec:
        externalUrl: http://alertmanager.demo.lab
    prometheus:
      prometheusSpec:
        externalUrl: http://prometheus.demo.lab
        scrapeInterval: 15s
        scrapeTimeout: 10s
        evaluationInterval: 15s
        retention: 6h
        ruleSelector:
          matchLabels:
            tier: cluster
        serviceMonitorSelector:
          matchLabels:
            tier: cluster
