---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    commonLabels:
      tier: cluster
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    grafana:
      grafana.ini:
        server:
          root_url: http://grafana.demo.lab
    alertmanager:
      alertmanagerSpec:
        externalUrl: http://alertmanager.demo.lab
    prometheus:
      prometheusSpec:
        externalUrl: http://prometheus.demo.lab
        scrapeInterval: 15s
        scrapeTimeout: 10s
        evaluationInterval: 15s
        retention: 6h
        ruleSelector:
          matchLabels:
            tier: cluster
        serviceMonitorSelector:
          matchLabels:
            tier: cluster
