---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/istio-system/
- ../../base/metallb-system/
- ../../base/jaeger/
- ../../base/bookinfo/
patchesStrategicMerge:
- istio-operator-patch.yaml
- metallb-patch.yaml
- jaeger-operator-patch.yaml
