---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/istio-system/
- ../../base/metallb-system/
- ../../base/cert-manager/
- ../../base/monitoring/
- ../../base/jaeger/
- ../../base/bookinfo/
resources:
- gateway.yaml
- istio-prometheus.yaml
- prometheus-istio-federation.yaml
- grafana-vs.yaml
- prometheus-vs.yaml
- istio-prometheus-vs.yaml
- alertmanager-vs.yaml
patchesStrategicMerge:
- istio-operator-patch.yaml
- metallb-patch.yaml
- kube-prometheus-stack-patch.yaml
- jaeger-operator-patch.yaml
- bookinfo-vs-patch.yaml
- flux-prometheus.yaml
- helm-operator-prometheus.yaml
