---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/istio-system/
- ../../base/metallb-system/
- ../../base/cert-manager/
- ../../base/monitoring/
- ../../base/jaeger/
- ../../base/kiali/
- ../../base/bookinfo/
resources:
- gateway.yaml
- istio-prometheus-sa.yaml
- istio-prometheus-crb.yaml
- istio-prometheus.yaml
- istio-prometheus-servicemonitor1.yaml
- istio-prometheus-servicemonitor2.yaml
- istio-prometheus-servicemonitor3.yaml
- istio-prometheus-service.yaml
- istio-prometheus-rules.yaml
- prometheus-istio-federation.yaml
- grafana-vs.yaml
- prometheus-vs.yaml
- istio-prometheus-vs.yaml
- alertmanager-vs.yaml
- flux-prometheus-servicemonitor.yaml
- flux-prometheus-rules.yaml
- helm-operator-prometheus-servicemonitor.yaml
- helm-operator-prometheus-rules.yaml
- tracing-vs.yaml
- kiali-vs.yaml
patchesStrategicMerge:
- istio-operator-patch.yaml
- metallb-patch.yaml
- kube-prometheus-stack-patch.yaml
- jaeger-operator-patch.yaml
- kiali-operator-patch.yaml
- bookinfo-vs-patch.yaml
