---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    repository: https://charts.bitnami.com/bitnami/
    name: metallb
    version: 1.0.1
  values:
    prometheus:
      enabled: true
      prometheusRule:
        enabled: false
    configInline: |-
      address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.77.100-192.168.77.110
