---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  values:
    prometheus:
      enabled: true
      prometheusRule:
        enabled: false
    configInline: |-
      address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.77.90-192.168.77.95
      - name: production
        protocol: layer2
        addresses:
          - 192.168.77.100-192.168.77.110
