---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  releaseName: kiali-server
  chart:
    repository: https://kiali.org/helm-charts
    name: kiali-server
