---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  releaseName: kiali-server
  chart:
    git: https://github.com/kiali/helm-charts
    ref: master
    path: kiali-server
