---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - example.com
    - www.example.com
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-issuer
