name: Validate Scenarios
on: [pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate kustomization
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.18.9
          kustomize: 3.8.4
          helmv3: 3.2.1
          command: |
            echo "Validating kustomize istio-demo scenario..."
            #kustomize build scenarios/istio-demo | kubeval --strict --ignore-missing-schemas
            echo "Validating kustomize istio-default scenario..."
            #kustomize build scenarios/istio-production | kubeval --strict --ignore-missing-schemas
